# Generated by Django 4.2.5 on 2023-10-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
