# Generated by Django 4.2.5 on 2023-10-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_lateloan_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateloan',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
