# Generated by Django 4.2.5 on 2023-11-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_author_suscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Bibliotecario'), (2, 'Catalogador'), (3, 'Lector'), (4, 'Administrador')], default=3),
            preserve_default=False,
        ),
    ]
