# Generated by Django 4.2.5 on 2023-10-27 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_remove_book_editorial_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.shelf')),
            ],
        ),
        migrations.CreateModel(
            name='BookLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.copy')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.section')),
            ],
        ),
    ]
