# Generated by Django 4.2.5 on 2023-10-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='number',
            field=models.CharField(max_length=3),
        ),
    ]
